# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tambahPesananWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
import iopesanan
import datetime


class tambahPesananUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.title_tambahPesanan = QtWidgets.QLabel(self.centralwidget)
        self.title_tambahPesanan.setGeometry(QtCore.QRect(230, 50, 180, 21))
        self.title_tambahPesanan.setObjectName("title_tambahPesanan")

        # Customer ID
        self.label_customerID = QtWidgets.QLabel(self.centralwidget)
        self.label_customerID.setGeometry(QtCore.QRect(200, 120, 61, 16))
        self.label_customerID.setObjectName("label_customerID")
        self.input_customerID = QtWidgets.QLineEdit(self.centralwidget)
        self.input_customerID.setGeometry(QtCore.QRect(320, 120, 113, 20))
        self.input_customerID.setObjectName("input_customerID")

        # Berat
        self.label_berat = QtWidgets.QLabel(self.centralwidget)
        self.label_berat.setGeometry(QtCore.QRect(200, 150, 61, 16))
        self.label_berat.setObjectName("label_berat")
        self.input_Berat = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.input_Berat.setGeometry(QtCore.QRect(320, 150, 62, 22))
        self.input_Berat.setObjectName("input_Berat")

        # Cucian
        self.label_cucian = QtWidgets.QLabel(self.centralwidget)
        self.label_cucian.setGeometry(QtCore.QRect(200, 180, 61, 16))
        self.label_cucian.setObjectName("label_cucian")
        self.input_cucian = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.input_cucian.setGeometry(QtCore.QRect(320, 180, 111, 71))
        self.input_cucian.setObjectName("input_cucian")

        # Jenis Layanan
        self.label_jenisLayanan = QtWidgets.QLabel(self.centralwidget)
        self.label_jenisLayanan.setGeometry(QtCore.QRect(200, 270, 71, 16))
        self.label_jenisLayanan.setObjectName("label_jenisLayanan")
        self.comboBox_jenisLayanan = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_jenisLayanan.setGeometry(QtCore.QRect(320, 270, 69, 22))
        self.comboBox_jenisLayanan.setObjectName("comboBox_jenisLayanan")
        self.comboBox_jenisLayanan.addItem("")
        self.comboBox_jenisLayanan.addItem("")
        self.comboBox_jenisLayanan.addItem("")

        # Cara Penyerahan
        self.label_caraPenyerahan = QtWidgets.QLabel(self.centralwidget)
        self.label_caraPenyerahan.setGeometry(QtCore.QRect(200, 300, 91, 16))
        self.label_caraPenyerahan.setObjectName("label_caraPenyerahan")
        self.comboBox_caraPenyerahan = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_caraPenyerahan.setGeometry(QtCore.QRect(320, 300, 69, 22))
        self.comboBox_caraPenyerahan.setObjectName("comboBox_caraPenyerahan")
        self.comboBox_caraPenyerahan.addItem("")
        self.comboBox_caraPenyerahan.addItem("")
        
        self.submitPesanan = QtWidgets.QPushButton(self.centralwidget)
        self.submitPesanan.setGeometry(QtCore.QRect(200, 380, 231, 31))
        self.submitPesanan.setObjectName("submitPesanan")
        self.submitPesanan.clicked.connect(self.check_addPesananinput)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def check_addPesananinput(self):
        self.msg = QtWidgets.QMessageBox()

        if self.input_customerID.text().isdigit():
            iopesanan.tambahPesanan(self.input_customerID.text(), self.input_Berat.text(), self.input_cucian.toPlainText(), 'Dalam antrean', int(round(self.input_Berat.value() * 7000.00)), 'Belum lunas', self.comboBox_jenisLayanan.currentText(), datetime.datetime.now().strftime("%x"), self.comboBox_caraPenyerahan.currentText())
            self.msg.setText('Pesanan berhasil ditambahkan.')
            self.msg.exec_()
        else:
            self.msg.setText('Customer ID harus berupa integer.')
            self.msg.exec_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_berat.setText(_translate("MainWindow", "Berat (kg)"))
        self.label_caraPenyerahan.setText(_translate("MainWindow", "Cara Penyerahan"))
        self.label_cucian.setText(_translate("MainWindow", "Cucian"))
        self.label_customerID.setText(_translate("MainWindow", "Customer ID"))
        self.label_jenisLayanan.setText(_translate("MainWindow", "Jenis Layanan"))
        self.title_tambahPesanan.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Tambah Pesanan</span></p></body></html>"))
        self.comboBox_caraPenyerahan.setItemText(0, _translate("MainWindow", "Diambil"))
        self.comboBox_caraPenyerahan.setItemText(1, _translate("MainWindow", "Diantar"))
        self.comboBox_jenisLayanan.setItemText(0, _translate("MainWindow", "Lavender"))
        self.comboBox_jenisLayanan.setItemText(1, _translate("MainWindow", "Rose"))
        self.comboBox_jenisLayanan.setItemText(2, _translate("MainWindow", "Vanilla"))
        self.submitPesanan.setText(_translate("MainWindow", "Tambah Pesanan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = tambahPesananUI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
